### ISSUE TITLE
New Zen update broke the effect position

### ISSUE THREAD

**Issue by jcnnik** [danm36/zen-browser-private-browsing-toolbar-highlighting#5] opened 2024-09-17 10:20 UTC
title

**Comment by danm36** [comment] 2024-09-17 19:07
Hmm, I just updated to 1.0.1-a1 and it looks (mostly) fine for me? The main things I'm noticing is the private mode icon is now a lot bigger and that the highlighted border gets clipped with rounded edges, which I feel might be a Zen-specific issue.

![image](https://github.com/user-attachments/assets/279d5ca6-8e67-4606-a144-b9f354ac49c3)

While I will aim to get the icon fixed ASAP and try to see if I can find a workaround for the border, if your issue is worse than what's in the picture, I also want to double check that you're not inadvertently running into a possible mod conflict? In my case, I'm currently running just four mods - Floating URLBar, Uniform Workspaces Button, Bookmark Toolbar Tweaks and this mod.

**Comment by jcnnik** [comment] 2024-09-17 19:18
I am talking about the top left corner which has no purple effect

**Comment by Veriiix** [comment] 2024-09-17 19:20
sry

**Comment by astro-ray** [comment] 2024-09-18 16:32
In the screenshot on the theme store, the gradient expands till the sidebar, but not in the new update. Is that an intended behaviour?

**Comment by danm36** [comment] 2024-09-18 19:35
> I am talking about the top left corner which has no purple effect

I gotcha. I'll send a fix PR in shortly.

> In the screenshot on the theme store, the gradient expands till the sidebar, but not in the new update. Is that an intended behaviour?

No, when this was first implemented, the sidebar didn't go all the way up to the top of the app like it does now. The CSS only targets the navbar, but that excludes the sidebar. As mentioned above, I'll try to get a fix in soon.

**Comment by danm36** [comment] 2024-09-18 20:27
Pull Request is in with a fix so that the gradient/solid block is now guaranteed to cross the entire top of the browser, regardless of what the Zen team do in the future. And now we wait.

I overhauled the settings too now since Zen supports dropdown lists, This should also mean that adding more settings, colors etc won't swamp your settings page with a hundred billion options. As far as I can tell, this will be the first theme to properly utilize them!

**Comment by danm36** [comment] 2024-09-20 09:01
Can confirm the fix is in. I'm one of the first users of the new preferences system, so if you notice that your colors have disappeared, check the Zen Mods area of your settings. Zen 1.0.1-a2 doesn't support initial/default values, but the next release will.

**Closed as completed by danm36** 2024-09-20 09:01 UTC
Labels: bug
